---
version: '3.7'

services:
  nginx:
    image: nexus.awide.io/docker-private/platform/release/reverse-proxy_awide:${PLATFORM_VERSION}
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "4222:4223"
      - "4223:4223"
      - "5666:5666"
    environment:
      - DOMAIN=${DOMAIN}
      - PG_ACL_LIST=0.0.0.0/0
      - SSL_CERT=${SSL_CERT}
      - SSL_CERT_KEY=${SSL_CERT_KEY}
      - SECURE_LINK_MD5=${SECURE_LINK_MD5}
    #entrypoint: sleep 3600
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - nats
      - pg_configurator
      - frontend
      - backend
    restart: always

  nats:
    image: nexus.awide.io/docker-private/platform/release/nats:${PLATFORM_VERSION}
    container_name: nats
    environment:
      NATS_USER: ${NATS_USER}
      NATS_PASSWORD: ${NATS_PASSWORD}
      SSL_CERT: ${SSL_CERT}
      SSL_CERT_KEY: ${SSL_CERT_KEY}
    volumes:
      - ./nats-data:/data
      - ./nginx/ssl:/etc/nats/ssl
    restart: always

  pg_explain:
    image: nexus.awide.io/docker-private/platform/release/pg-explain:${PLATFORM_VERSION}
    container_name: pg_explain
    security_opt:
      - seccomp:unconfined
    environment:
      - PG_HOST=tns_db
      - PG_PORT=5432
      - PG_USER=monitor
      - PG_PASSWORD=monitor_password
      - PG_DB=pg-monitor
      - PG_NAME=pg-monitor
      - MASTER_PORT=8000
      - WORKER_PORT=4200
      - GENERATE_KEY=${ENCRYPT_KEY}
    restart: always
    depends_on:
      tns_migrations:
        condition: service_completed_successfully

  pg_monitor_dispatcher:
    image: nexus.awide.io/docker-private/platform/release/pg-monitor:${PLATFORM_VERSION}
    container_name: pg_monitor_dispatcher
    security_opt:
      - seccomp:unconfined
    environment:
      - PG_HOST=tns_db
      - PG_PORT=5432
      - PG_USER=monitor
      - PG_PASSWORD=monitor_password
      - PG_DB=pg-monitor
      - PG_NAME=pg-monitor
      - ROLE=dispatcher
      - GENERATE_KEY=${ENCRYPT_KEY}
    volumes:
        - ./ssh:/opt/pg-monitor/ssh_keys
    restart: always
    depends_on:
      tns_migrations:
        condition: service_completed_successfully

  pg_monitor_collector:
      image: nexus.awide.io/docker-private/platform/release/pg-monitor:${PLATFORM_VERSION}
      container_name: pg_monitor_collector
      security_opt:
        - seccomp:unconfined
      environment:
        - PG_HOST=tns_db
        - PG_PORT=5432
        - PG_USER=monitor
        - PG_PASSWORD=monitor_password
        - PG_DB=pg-monitor
        - PG_NAME=pg-monitor
        - ROLE=collector
        - GENERATE_KEY=${ENCRYPT_KEY}
        - NODE_EXTRA_CA_CERTS=/opt/pg-monitor/ssl/${SSL_CERT}
        - S3_PERIOD=300
      volumes:
        - ./ssh:/opt/pg-monitor/ssh_keys
        - ./nginx/ssl:/opt/pg-monitor/ssl
      restart: always
      depends_on:
        tns_migrations:
          condition: service_completed_successfully

  tns_db:
    image: nexus.awide.io/docker-private/platform/release/tns_db:${PLATFORM_VERSION}
    container_name: tns_db
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=monitor
      - POSTGRES_PASSWORD=monitor_password
      - POSTGRES_DB=pg-monitor
    volumes:
      - ./tnsdb/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s
    restart: always
    shm_size: 1gb

  tns_migrations:
    image: nexus.awide.io/docker-private/platform/release/tns_migrations:${PLATFORM_VERSION}
    container_name: tns_migrations
    environment:
      - POSTGRES_USER=monitor
      - POSTGRES_PASSWORD=monitor_password
      - POSTGRES_HOST=tns_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pg-monitor
    depends_on:
      tns_db:
        condition: service_healthy

  pg_configurator:
    image: nexus.awide.io/docker-private/platform/release/pg_configurator:${PLATFORM_VERSION}
    container_name: pg_configurator
    restart: always

  frontend:
    image: nexus.awide.io/docker-private/platform/release/pmmfront_angmat_awide:${PLATFORM_VERSION}
    container_name: frontend
    environment:
      - ADVANCED_ANALYTICS=${ADVANCED_ANALYTICS}
    restart: always

  backend:
    image: nexus.awide.io/docker-private/platform/release/postgres-management-suite/awide/backend:${PLATFORM_VERSION}
    container_name: backend
    environment:
      - PMA_SERVER_RESTAPI_HOST=0.0.0.0
      - PMA_SERVER_RESTAPI_PORT=5666
      - PMA_SERVER_PG_CONFIGURATOR_ENDPOINT=http://pg_configurator:7777
      - PMA_SERVER_PG_ANON_ENDPOINT=http://pg_anon:8000
      - PMA_SERVER_PG_ANON_BACKEND_CALLBACK_ENDPOINT=http://backend:5666
      - PMA_SERVER_NGINX_PMA_GATEWAY=https://${DOMAIN}:8443
      - PMA_SERVER_NGINX_SECRET=${SECURE_LINK_MD5}
      - PMA_SERVER_SECRET_KEY_JWT=${SECRET_TOKEN}
      # PG pooler connection:
      - PMA_SERVER_OPSPG_HOST=pg_bouncer
      - PMA_SERVER_OPSPG_PORT=6432
      - PMA_SERVER_OPSPG_USERNAME=pmm
      - PMA_SERVER_OPSPG_PASSWORD=${DB_PASSWORD}
      # Nats connection:
      - PMA_SERVER_NATS_ENDPOINT=tls://${DOMAIN}:4223
      - PMA_SERVER_NATS_INTERNAL_ENDPOINT=tcp://nats:4223
      - PMA_SERVER_NATS_USER_NAME=${NATS_USER}
      - PMA_SERVER_NATS_USER_PASSWORD=${NATS_PASSWORD}
      - PMA_SERVER_NATS_TLS_INSECURE=${TLS_INSECURE}
      - PMA_SERVER_NATS_REQUEST_RESPONSE_TOPIC_NAME=A2S_REQUEST_RESPONSE
      - PMA_SERVER_NATS_AGENT2SERVER_TOPIC_NAME=A2S_NOTIFICATIONS
      - PMA_SERVER_NATS_SERVER2SERVER_TOPIC_NAME=S2S_NOTIFICATIONS
      - PMA_SERVER_NATS_CLUSTER_ID=awidelabs
      # S3 connection:
      # - PMA_SERVER_S3_USER=${S3_USER}
      # - PMA_SERVER_S3_PASSWORD=${S3_PASSWORD}
      # - PMA_SERVER_S3_ENDPOINT=${S3_ENDPOINT}
      # - PMA_SERVER_S3_TLS_INSECURE=${S3_TLS_INSECURE}
      # AA connection
      - PMA_SERVER_PG_EXPLAIN_URL=http://pg_explain:4200
      # - PMA_SERVER_LOGGING_LEVEL=trace
      - PMA_SERVER_INNER_ENVIRONMENT=true
    restart: always
    depends_on:
      maindb_migrations:
        condition: service_completed_successfully
      operdb_migrations:
        condition: service_completed_successfully
      pg_bouncer:
        condition: service_healthy

  keeper:
    image: nexus.awide.io/docker-private/platform/release/postgres-management-suite/awide/keeper:${PLATFORM_VERSION}
    container_name: keeper
    environment:
      # Processing:
      - PMA_KEEPER_OPS_NUMBERSEVENTSUBSCRIBERS=3
      # PG pooler connection:
      - PMA_KEEPER_OPSPG_HOST=pg_bouncer
      - PMA_KEEPER_OPSPG_PORT=6432
      - PMA_KEEPER_OPSPG_USERNAME=pmm
      - PMA_KEEPER_OPSPG_PASSWORD=${DB_PASSWORD}
      # Nats connection:
      - PMA_KEEPER_NATS_ENDPOINT=tcp://nats:4223
      - PMA_KEEPER_NATS_REQUEST_RESPONSE_TOPIC_NAME=A2S_REQUEST_RESPONSE
      - PMA_KEEPER_NATS_AGENT2SERVER_TOPIC_NAME=A2S_NOTIFICATIONS
      - PMA_KEEPER_NATS_CLUSTER_ID=awidelabs
      - PMA_KEEPER_NATS_GROUPMETRIC_NAME=queue-metric
      - PMA_KEEPER_NATS_DURABLE_NAME=awidelabs-durable
      - PMA_KEEPER_NATS_USER_NAME=${NATS_USER}
      - PMA_KEEPER_NATS_USER_PASSWORD=${NATS_PASSWORD}
      # - PMA_KEEPER_LOGGING_LEVEL=trace
    restart: always
    depends_on:
      - backend
  operdb_migrations:
    image: nexus.awide.io/docker-private/platform/release/operdb:${PLATFORM_VERSION}
    container_name: operdb_migrations
    environment:
      - POSTGRES_USER=pmm
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=operdb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pma
      - DOMAIN=nginx
      - SYSTEM_USER_EMAIL=${SYSTEM_USER_EMAIL}
      - SYSTEM_USER_NAME=${SYSTEM_USER_NAME}
    depends_on:
      operdb:
        condition: service_healthy

  operdb:
    image: nexus.awide.io/docker-private/platform/release/operdb_postgres:${PLATFORM_VERSION}
    container_name: operdb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./operdb:/var/lib/postgresql/awide-postgresql-17/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    shm_size: 1gb

  maindb_migrations:
    image: nexus.awide.io/docker-private/platform/release/maindb:${PLATFORM_VERSION}
    container_name: maindb_migrations
    environment:
      - POSTGRES_USER=pmm
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=maindb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=maindb
      - DOMAIN=${DOMAIN}
      - SYSTEM_USER_EMAIL=${SYSTEM_USER_EMAIL}
      - SYSTEM_USER_NAME=${SYSTEM_USER_NAME}
    depends_on:
      maindb:
        condition: service_healthy

  maindb:
    image: nexus.awide.io/docker-private/platform/release/maindb_postgres:${PLATFORM_VERSION}
    container_name: maindb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./maindb:/var/lib/postgresql/awide-postgresql-17/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    shm_size: 1gb

  pg_bouncer:
    image: nexus.awide.io/docker-private/platform/release/pg_bouncer:${PLATFORM_VERSION}
    container_name: pg_bouncer
    environment:
      - POSTGRES_USER=pmm
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=maindb
    volumes:
      - ./pg_bouncer:/opt/awide/etc/pgbouncer
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d maindb -h 127.0.0.1 -p 6432 -c 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    depends_on:
      maindb_migrations:
        condition: service_completed_successfully
      operdb_migrations:
        condition: service_completed_successfully
    restart: always

  pg_anon:
    image: nexus.awide.io/docker-private/platform/release/pg_anon:${PLATFORM_VERSION}
    container_name: pg_anon
    volumes:
      - ./pg_anon:/pg_anon/output
      - ./pg_anon_runs:/pg_anon/runs
    restart: always

  swagger_ui:
    image: nexus.awide.io/docker-private/platform/release/swagger-ui:${PLATFORM_VERSION}
    container_name: swagger_ui
    environment:
      - URL=/integration/definition/yaml
    restart: always